version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch-7.14.1
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elknetwork

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash-7.14.1
    ports: 
      - "9600:9600"
      - "8089:8089"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./reddit_vm.csv:/usr/share/reddit_vm.csv
    depends_on:
      - elasticsearch
    networks: 
      - elknetwork
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana-7.14.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elknetwork

networks:
  elknetwork:
    driver: bridge
