version: "3.7"

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch-7.14.1
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elknetwork
  

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash-7.14.1
    hostname: logstash
    ports: 
      - "9600:9600"
      - "8089:8089"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks: 
      - elknetwork
  
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana-7.14.1
    ports:
      - "5601:5601"
    hostname: kibana
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork


networks:
  elknetwork:
    driver: bridge
